spring:
  kafka:
    # 消费者
    consumer:
    #  group-id: foo
    #  auto-offset-reset: earliest
      bootstrap-servers: 10.20.178.137:9092
    # 生产者
    producer:
      bootstrap-servers: 10.20.178.137:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
